CREATE TABLE alunos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(150) NOT NULL,
    matricula VARCHAR(30) NOT NULL,
    nome VARCHAR(120) NOT NULL,
    CONSTRAINT uk_alunos_matricula UNIQUE (matricula)
);

CREATE TABLE ambientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capacidade INTEGER NOT NULL,
    nome VARCHAR(100) NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    CONSTRAINT ck_ambientes_tipo CHECK (
        tipo IN ('SALA_DE_AULA', 'LABORATORIO', 'SALA_DE_ESTUDOS')
    )
);

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo BOOLEAN NOT NULL,
    login VARCHAR(60) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    CONSTRAINT uk_usuarios_login UNIQUE (login)
);

CREATE TABLE presencas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entrada TIMESTAMP(6) NOT NULL,
    saida TIMESTAMP(6),
    aluno_id BIGINT NOT NULL,
    ambiente_id BIGINT NOT NULL,
    CONSTRAINT fk_presencas_aluno
        FOREIGN KEY (aluno_id) REFERENCES alunos (id),
    CONSTRAINT fk_presencas_ambiente
        FOREIGN KEY (ambiente_id) REFERENCES ambientes (id)
);

CREATE INDEX idx_presencas_aluno_saida
    ON presencas (aluno_id, saida);

CREATE INDEX idx_presencas_ambiente_saida
    ON presencas (ambiente_id, saida);
